### User sign-up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
  "name": "Jimmy Kigen",
  "company": "Company name",
  "address": "Some address Sydney",
  "phone": "0721573423",
  "email": "jimmy@gmail.com",
  "password": "password"
}

### User sign-in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
  "email": "jimmy@gmail.com",
  "password": "password"
}

### Get user profile endpoint
GET http://localhost:3001/v1/user
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImppbW15QGdtYWlsLmNvbSIsImlhdCI6MTcxNjg3ODM3OCwiZXhwIjoxNzE2ODgwMTc4fQ.1pc_DJTJnkXrOy62RJ4JFlnV9eH0tNN8Vw3j1Ty15yM
### Token routes


### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImppbW15QGdtYWlsLmNvbSIsImlhdCI6MTcxNjg3ODM3OCwiZXhwIjoxNzE2ODgwMTc4fQ.1pc_DJTJnkXrOy62RJ4JFlnV9eH0tNN8Vw3j1Ty15yM