### User sign-up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
  "name": "Jimmy Kigen",
  "company": "Company name",
  "address": "Some address Sydney",
  "phone": "0721573423",
  "email": "jimmy@gmail.com",
  "password": "password"
}

### User sign-in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
  "email": "jimmy@gmail.com",
  "password": "password"
}

### Get user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImppbW15QGdtYWlsLmNvbSIsImlhdCI6MTcxNjgxMTE4OSwiZXhwIjoxNzE2ODEyOTg5fQ.P31lbRku3yTZb5QgJ-iLNRQH-MSr3N9c6gCNKQqQ048

### Token routes